### ISSUE TITLE
It would be cool if this worked with git-rev-replace

### ISSUE THREAD

**Issue by shawn-simon** [mikaelbr/gulp-gitshasuffix#3]
You'd just have to append a few properties on the file object.
```
	file.revOrigPath = file.path;
	file.revOrigBase = file.base;
```

**Comment by shawn-simon** [comment]
pls

**Comment by mikaelbr** [comment]
Hi, and sorry for the late response. I've added support for this in the master branch now. You can test it out by doing `npm i mikaelbr/gulp-gitshasuffix` and let me know how it works out. If everything is fine I'll release a new version. Sounds good?

**Comment by shawn-simon** [comment]
hrm. haven't tried that version, i used this code and it worked. https://github.com/shawn-simon/gulp-gitshasuffix/commit/f272d6fbacef047d47faa4c9afa2323a0ec47700 I can test when I have sometime... one day...

**Comment by mikaelbr** [comment]
```
➜  gulp-gitshasuffix git:(master) npm publish
+ gulp-gitshasuffix@1.0.0
```

Now supported!
